name: Tidy Go Modules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: '1.19' }
      - run: |
          cd screp-service
          go mod tidy
      - run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add go.mod go.sum
          git diff --quiet && echo 'No changes' || git commit -m 'chore: update Go module checksums'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
